### ISSUE TITLE
Not able to build - cannot find file - konfyt.pro

### ISSUE THREAD

**Issue by TobbeT** [noedigcode/konfyt#12]
Hi,
I try to build this on my Linux Mint XFCE computer but I don't manage. When I type qmake ../konfyt.pro in the build directory I get this message: Cannot find file: ../konfyt.pro

When you have time. I asked falkTX if he would put this on his KX Repos but not just now, or no plans for it.

Thanks

//Tobbe

**Comment by noedigcode** [comment]
Hi. You might be in the wrong directory.
When using your command `qmake ../konfyt.pro`, your directory structure should look like this:
![image](https://user-images.githubusercontent.com/11135749/67231906-83ede100-f440-11e9-9672-e413bc143cf9.png)
i.e. you should be in the build directory (or any name), which is a subdirectory of the konfyt source code directory.

If you are running the command directly from the konfyt source code directory (i.e. you are not in a subdirectory), the command should be `qmake konfyt.pro` (without the "`..`").

**Comment by TobbeT** [comment]
Hmm, no matter what directory I choose it doesn't work. I tried this from terminal:

tobbe@homestudio:~/Downloads/konfyt-testing/build$ qmake ../konfyt.pro
Project ERROR: Package jack not found
tobbe@homestudio:~/Downloads/konfyt-testing/build$

in the readme file it says g++ should I install something then. When I do a "apt search g++" I get tons of things.

And Jack, what jack? I have qjackctl installed, and Cadence from KXStudio.

**Comment by noedigcode** [comment]
So it looks like you have the correct directory now since it's not complaining about the .pro file anymore.

If QJackCtl is installed, then JACK is probably installed, but for building programs you need the development package also.
`libjack-jackd2-dev`
(This is if you have JACK2 installed. To confirm, check your JACK version (`jackd --version`). If I recall correctly, if the version number is larger than 1 (e.g. 1.9....) then it's JACK2, otherwise it is JACK 1. For JACK 1, the package is simply libjack-dev).

You also need:
libfluidsynth-dev
liblscp6
liblscp-dev
linuxsampler
g++ (just simply installing "g++" should do the trick)

**Comment by TobbeT** [comment]
Thanks so much for your time and help. I can say that I'm *not* good at
this. Now I get this error. I have installed everything you mention.

tobbe@homestudio:~/konfyt-master$ qmake konfyt.pro
tobbe@homestudio:~/konfyt-master$ make



*/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/mainwindow.ui -o
ui_mainwindow.hmake: /usr/lib/x86_64-linux-gnu/qt4/bin/uic: Command not
foundMakefile:470: recipe for target 'ui_mainwindow.h' failedmake: ***
[ui_mainwindow.h] Error 127*

I see it creates the Makefile with the hammer icon.

Should I do this as root?

Is it hard to make a deb installation?

*Med vänliga hälsningar*
Torbjörn Törnqvist
Litjärnberget 120
880 50 BACKE


Den tis 22 okt. 2019 kl 12:00 skrev Gideon van der Kolf <
notifications@github.com>:

**Comment by noedigcode** [comment]
You are building with Qt4. You should use Qt5.
Delete everything in the build directory first (or `make clean` if you are in the source code directory and do not have a separate build directory).
Then try the qmake command but specify Qt5:
`qmake --qt=5 konfyt.pro` (or `qmake --qt=5 ../konfyt.pro` if you are in a build subdirectory)
Then try `make` again.
If qmake command fails, you have to install Qt5 first. I'm not at a Linux PC now, but I think the Qt5 packages are:
qt5-qmake
libqt5core5a

**Comment by TobbeT** [comment]
...and the problem continues. I don't wanna waste your time...last chance
and I leave it. Why something so simple to install a program can be so
frustrating when you not knowing what you suppose to do to make it work.

What am I missing now then?

tobbe@homestudio:~/konfyt-master$ qmake --qt=5 konfyt.pro
sh: 1: /usr/lib/qt5/bin/rcc: not found
sh: 1: /usr/lib/qt5/bin/uic: not found
sh: 1: /usr/lib/qt5/bin/uic: not found
sh: 1: /usr/lib/qt5/bin/uic: not found
sh: 1: /usr/lib/qt5/bin/uic: not found

*Distro: *Linux Mint XFCE 19.01 Tessa
*Base: *Ubuntu 18.04 Bionic
*Kernel: *lowlatency 5.0.0-31 (Updated today)

*Med vänliga hälsningar*
Torbjörn Törnqvist
Litjärnberget 120
880 50 BACKE


Den tis 22 okt. 2019 kl 15:36 skrev Gideon van der Kolf <
notifications@github.com>:

**Comment by noedigcode** [comment]
Don't worry, you're not wasting my time.
I didn't give you the proper packages for Qt5 development.
Try installing `qt5-default`. This should install a whole bunch of stuff needed by Qt5, and also make it the default when you build using qmake.
Then we take it from there.

**Comment by noedigcode** [comment]
I created a pre-built binary that you can try if you want.
https://github.com/noedigcode/konfyt/releases/tag/v1.0.0-testing

**Comment by TobbeT** [comment]
Yay! Hi five 👍👍👍👍👍

Did this: chmod u+x konfyt-1.0.0-testing-x64
and then: ./konfyt-1.0.0-testing-x64

and love and behold...it works. Thanks a million. Now it's time to learn
the program.

*Med vänliga hälsningar*
Torbjörn Törnqvist
Litjärnberget 120
880 50 BACKE


Den tis 22 okt. 2019 kl 18:32 skrev Gideon van der Kolf <
notifications@github.com>:
