### ISSUE TITLE
black text on black background when system theme is bright

### ISSUE THREAD

**Issue by BrainDamage** [noedigcode/konfyt#15]
My system theme is bright, and the left column is unusable due to having no contrast:
![Screenshot_20191102_131905](https://user-images.githubusercontent.com/50474/68070825-9ab30280-fd73-11e9-9f96-48daabba973c.png)

**Comment by noedigcode** [comment]
I also just realized this with the newer Qt themes. Will address this shortly.

**Comment by noedigcode** [comment]
Please check if the latest commit works for you.

**Comment by BrainDamage** [comment]
fixed, thanks
