### ISSUE TITLE
feature request: use XDG base spec

### ISSUE THREAD

**Issue by BrainDamage** [noedigcode/konfyt#16]
In order to cleanup dotfile clutter, making backup easier and giving a standard, [XDG Base directory standard](https://standards.freedesktop.org/basedir-spec/latest/) was made.
The standard uses a common prefix for user dirs having either by default a well known path or either an env var chosen by the user, allowing flexibility if necessary ( env var can be overridden on a per-program basis if one needs so ).
For a third party project that tracks adoption, see the [Arch Wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support).

**Comment by noedigcode** [comment]
New commit on testing branch now uses the following paths by default:
Settings and database stored in XDG config path.
Default projects, patches and sounds directory is XDG documents path/Konfyt/...

However, the Settings dialog now contains dropdown boxes with XDG data path as options for projects, patches and sounds.

The first time you run the new version app, your settings and database from the old location (HOME/.konfyt) will be copied to the new location (XDG config path), and from then on the new location will be used.

**Comment by noedigcode** [comment]
New commit on testing branch now uses the following paths by default:
Settings and database stored in XDG config path.
Default projects, patches and sounds directory is XDG documents path/Konfyt/...

However, the Settings dialog now contains dropdown boxes with XDG data path as options for projects, patches and sounds.

The first time you run the new version app, your settings and database from the old location (HOME/.konfyt) will be copied to the new location (XDG config path), and from then on the new location will be used.
