### ISSUE TITLE
Using pre-compiled carla binaries

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#17]
Hi,

Very happy to see the new release and recent activity. I just switched to [pre-compiled carla binaries](https://kx.studio/Applications:Carla#Download) (much more stable!) and therefore, do not have any carla related packages installed. This now means I can't satisfy konfyt's requirements since I'm missing libcarla_standalone2.so

Is there anything that can be done?

Thanks in advance

**Comment by noedigcode** [comment]
Konfyt can now be built without Carla support (i.e. it will use Linuxsampler to load SFZs). A precompiled binary is available from releases. The readme contains instructions for building.

However, if you really do want to let Konfyt use Carla to load SFZs, just install Carla with your package manager. This should make the library available to Konfyt, but you should still be able to run your precompiled Carla binaries for other work.

**Comment by windowsrefund** [comment]
sweet!
