### ISSUE TITLE
Some zfs are not working

### ISSUE THREAD

**Issue by magjo67** [noedigcode/konfyt#22]
I am not sure it has to do with my setup.

Some zfs does not make any sound.
For example
https://github.com/sfzinstruments/BengtNilsson.HeadroomPiano

**Comment by noedigcode** [comment]
Unfortunately it seems that that sfz uses a lot of Sforzando/ARIA specific opcodes that are not supported by Linuxsampler or Carla. See the compatibility notes section in the readme.
You could have a go at inspecting the sfz file and trying to simplify it if you are brave, or ask whether someone on Linuxmusicians.com has any clue on how to simplify it.
When running it in Linuxsampler/QSampler or Carla, you will see the list of unsupported opcodes in the standard output.

**Comment by magjo67** [comment]
I guess I can try to remove som of the options in the sfz file to simplify.
But it would be great if konfyt automatically skipped the options that aren't supported.

**Comment by noedigcode** [comment]
Konfyt uses Linuxsampler or Carla as a backend to handle sfz files. These engines do try to ignore unsupported opcodes and sometimes it works out fine, but in this case there are either just too many or the sfz depends on them in such a way that it won't make sound without them, even if they are ignored.
It would have been nice if the creator of the sfz made a dumbed down variant for players that don't support the ARIA extensions. On the other hand, it would be nice if the Linux and open source sfz engines supported the ARIA extensions.

**Comment by noedigcode** [comment]
You could try sfizz (https://sfz.tools/sfizz/) and see if it brings you closer to success. The site has a nice list of supported opcodes, some of which include ARIA opcodes.

**Comment by magjo67** [comment]
Thanks
