### ISSUE TITLE
Konfyt not starting/running

### ISSUE THREAD

**Issue by tomcolley1962** [noedigcode/konfyt#24]
I've just installed Konfyt. Installation occurred without any error messages but I've been unable to open/start/run the software. Clicking the application desktop icon gets no response. System Monitor shows no sign of any process with a name like Konfyt.

After installation, I sought to meet the listed requirements. The only difficulty with requirements was Carla. Without breaking dependencies on my Ubuntu 20.04 system, I can only use Carla 2.1, not 2.4.3, which is currently recommended. I can't think what else might prevent the software running and I don't know how to get around this Carla version issue. Any suggestions or illumination as to whether my problem relates to the Carla version and/or how to fix it?

**Comment by noedigcode** [comment]
Can you try running `konfyt` from a terminal to see what output messages it gives?

**Comment by noedigcode** [comment]
The problem does indeed seem to be the older Carla library.
I have built a version with Carla 2.1 on Ubuntu 20.04 that you can try if you'd like:
[konfyt_1.2.2-dev-2023-01-05.1-ubuntu20.04-carla2.1.0-1_amd64.zip](https://github.com/noedigcode/konfyt/files/10350223/konfyt_1.2.2-dev-2023-01-05.1-ubuntu20.04-carla2.1.0-1_amd64.zip)

**Comment by tomcolley1962** [comment]
Thanks @noedigcode for the quick & helpful replies
> Can you try running `konfyt` from a terminal to see what output messages it gives?

```
~$ konfyt
konfyt: symbol lookup error: konfyt: undefined symbol: carla_standalone_host_init
```
> The problem does indeed seem to be the older Carla library.
I have built a version with Carla 2.1 on Ubuntu 20.04 that you can try if you'd like:
[konfyt_1.2.2-dev-2023-01-05.1-ubuntu20.04-carla2.1.0-1_amd64.zip](https://github.com/noedigcode/konfyt/files/10350223/konfyt_1.2.2-dev-2023-01-05.1-ubuntu20.04-carla2.1.0-1_amd64.zip)

I've downloaded that file and used it to install Konfyt. The application opens and reads soundfonts from the directory I've nominated. I haven't done anything else yet but all looks good at this point. Thanks!
