### ISSUE TITLE
Feature Request: adding more Patch entries in Triggers Action menu

### ISSUE THREAD

**Issue by Gerbmouse** [noedigcode/konfyt#25]
There are only 8 Patches available in Triggers to assign Midi Program CChanges to. Would it be easily possible to increase this to at least 16?

**Comment by noedigcode** [comment]
The number of patches available in the Triggers list has been increased to 16. You can find the update in the latest master branch for now. A release will only be made in April.

Also, with the "Program change messages with no bank select change patches" option enabled (bottom of the Triggers screen), Konfyt will change patches based on program messages received, even for values exceeding 16.

**Comment by Gerbmouse** [comment]
Wow, you are my absolute hero ;-)
Feature requested, feature implemented, changes pulled and compiled and tested all within 12 hours. What a great support. Thank you very much!
