### ISSUE TITLE
Feature Request: Adding Same Midi Outport in patch multiple times

### ISSUE THREAD

**Issue by Gerbmouse** [noedigcode/konfyt#26]
To explain: I want to use konfy together with setBfree using one master keyboard (sending on Midi channal 1). SetBfree uses 3 Midi channels for Pedal, Lower and Upper Manual. I'd like to split my Keyboard to send a lower range to Pedal, another range to Lower and the rest to Upper Manual. At the moment I create 3 Midi Out Busses and use them in one patch setting them to different Midi Out channels thus I have to connect three individual Midi port connections to setBfree Midi input. It would be nice to be able to use one Miidi out port multiple (at least 3) times in a patch using different split points and Midi channels for each port.

**Comment by noedigcode** [comment]
I'll look into this.

**Comment by noedigcode** [comment]
On the Testing branch, multiple of the same MIDI-out or audio-in port layers can now be added to a patch. I have only done limited testing thus far, but if you are keen, you can try it out.

**Comment by Gerbmouse** [comment]
Great news! Works very well on a first glance. I have reworked all my Organ patches so far and will use it daily in my home setup thus no need for you to make further test. Will come back if anything strange happens.
BTW: Is theren any mean to make a donation? I'm very grateful for Konfyt.
