### ISSUE TITLE
not able to remove / delete patches from patch list

### ISSUE THREAD

**Issue by Gerbmouse** [noedigcode/konfyt#27]
I'm not able to delete patches from patch list by any means, the small x at the bottom is not working. Latest testing branch (6723d97dcda838e59bffcff24c7c4e994d0c0927). 

By chance I created a new patch by making a copy in the patch manu. I wanted to copy a layer of a patch to edit it. Maybe the patch menu should be located above the patch list to make it more clear it handles the patches not the layers. But this is no feature request for I now know the pitfall :-)

**Comment by noedigcode** [comment]
When you click the X button below the patch list, it opens a menu with a single item which you have to click in order to actually delete the patch. This is a kind of confirmation to prevent you from accidentally just deleting a patch.
Can you try it again and see if you notice the popup menu?

**Comment by Gerbmouse** [comment]
Oh yes, my bad! I will close the issiue, thanks.
