### ISSUE TITLE
Feature Request: Font Scaling

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#3]
While I suspect this is a QT-related shortcoming/annoyance, I'm just taking a wild stab at submitting this feature request. Would be so sweet to have some kind of slider or something to be able to increase font size as needed.

Thanks again for this awesome tool.

**Comment by windowsrefund** [comment]
N/M, just discovered the Qt5 Theme Settings tool

Background info here: http://www.webupd8.org/2015/11/configure-qt5-application-style-icons.html

**Comment by windowsrefund** [comment]
I may have spoke too soon as Konfyt doesn't appear to honor my font settings?

**Comment by noedigcode** [comment]
While I'm looking into this - on a hdpi monitor you can scale the whole GUI by setting the environment variable QT_SCALE_FACTOR, e.g.
```
export QT_SCALE_FACTOR=2
konfyt
```
This scales the whole GUI, however it sounds like you just want to make the fonts bigger. Will look into it.

**Comment by windowsrefund** [comment]
Yea, I tried that a few days ago as well but that just blows the entire GUI up. Earlier today, I came across QT_FONT_DPI which I intend to muck with later. Perhaps that will have the desired effect. I'll report back...

**Comment by windowsrefund** [comment]
Closing as I've decided to just get used to the font size :)

**Comment by noedigcode** [comment]
The testing branch now uses your Qt system font and should behave properly with different font sizes.
