### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#4]
Hello,

Thanks for the last exchange and work done to increase font sizes. I've been using the latest version from the testing branch and am still wishing I had a way to make the fonts somewhat larger. Some text within Konfyt is surely usable but other areas such as the filenames within the Library/Filesystem Tabs still feel quite (unnecessarily) small. I know we talked about qt5ctl and bumping font size in there, but increasing from 9 to 10 or 11 just makes my system look pretty horrible. Honestly, I'd prefer to not even mess with it.

Another thing that could be making the smaller text harder to read is the bright blue highlight against the white text. Changing the colors used here could go a long way toward readability.

When browsing my "Library", I'll click on a .sf2 and I see (most likely) some meta information below the Library panel. For example, I see "0-0 French Horn 1". What does 0-0 mean? I was thinking some range of valid MIDI notes perhaps? Even if I'm wrong here, that leads me to another killer feature request... Would it be possible to display a keyboard or something displaying that MIDI notes are actually assigned to a sound? This would be really helpful when browsing around new/unfamiliar soundfonts. All too often, a particular soundfont might only offer a small range of assigned notes which puts us in position where we're left to fish around. Again, maybe I'm misunderstanding the information already displayed.

Assuming an instrument has been added to the Patch List panel, it would be nice to see any MIDI channel(s) that have been assigned without having to right click and look at the filter.

The Global Volume slider could provide some feedback in terms of volume level. Or is it just basically 0 to 100% or something?

I think that's all for now. Thanks again. I think this software is awesome and see tons of potential for it.

**Comment by noedigcode** [comment]
1. Library/filesystem font
>  areas such as the filenames within the Library/Filesystem Tabs still feel quite (unnecessarily) small.

The font size of the library/filesystem lists should be the same as the rest of the GUI font. Are you saying that you'd want to make only the library/filesystem font larger, leaving the rest of the font small?

2. Library/filesystem selection colour
> Changing the colours used here could go a long way toward readability.

The selection colour is currently dictated by your system theme (although personally I find the white on blue quite pleasing), but I can definitely look at changing this in the stylesheets to ensure that it is readable on all systems.

3. SF2 program numbers
> What does 0-0 mean?

This refers to bank number and program number. This is how sounds are organised in SF2 soundfont files. This doesn't have much meaning inside Konfyt, as bank and program changes aren't used directly with SF2 files, but the info might still be useful as a reference when using other programs to work with SF2 files.

4. Instrument keyboard zones
> Would it be possible to display a keyboard or something displaying that MIDI notes are actually assigned to a sound?

This sounds cool, but is not a priority at present - it might even require an additional library to be used. This can be checked with a soundfont editor like Swami or Polyphone. Currently, it's just too much work for too little return.

5. Patch layers MIDI channel indication
> Assuming an instrument has been added to the Patch List panel, it would be nice to see any MIDI channel(s) that have been assigned without having to right click and look at the filter.

I'll look into this.

**Comment by windowsrefund** [comment]
> 1. Library/filesystem font
> 
> > areas such as the filenames within the Library/Filesystem Tabs still feel quite (unnecessarily) small.
> 
> The font size of the library/filesystem lists should be the same as the rest of the GUI font. Are you saying that you'd want to make only the library/filesystem font larger, leaving the rest of the font small?

Maybe I'll post a screenshot highlighting areas that could use a bump...

> 
> 1. Library/filesystem selection colour
> 
> > Changing the colours used here could go a long way toward readability.
> 
> The selection colour is currently dictated by your system theme (although personally I find the white on blue quite pleasing), but I can definitely look at changing this in the stylesheets to ensure that it is readable on all systems.

I should have thought of that although I'm not sure that blue background shows up anywhere on my system. That said, it's good information so I'll take a closer look at my box. Perhaps I can tweak something locally.

> 
> 1. SF2 program numbers
> 
> > What does 0-0 mean?
> 
> This refers to bank number and program number. This is how sounds are organised in SF2 soundfont files. This doesn't have much meaning inside Konfyt, as bank and program changes aren't used directly with SF2 files, but the info might still be useful as a reference when using other programs to work with SF2 files.
> 
> 1. Instrument keyboard zones
> 
> > Would it be possible to display a keyboard or something displaying that MIDI notes are actually assigned to a sound?
> 
> This sounds cool, but is not a priority at present - it might even require an additional library to be used. This can be checked with a soundfont editor like Swami or Polyphone. Currently, it's just too much work for too little return.
> 
> 1. Patch layers MIDI channel indication
> 
> > Assuming an instrument has been added to the Patch List panel, it would be nice to see any MIDI channel(s) that have been assigned without having to right click and look at the filter.
> 
> I'll look into this.

Thanks in advance

**Comment by noedigcode** [comment]
Closing issue as all points have been accounted for.
