### ISSUE TITLE
XRUN/Konfyt Crash when auditioning soundfonts

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#5]
Hello,

Konfyt is crashing when loading some soundfonts (sf2). Here's what I see when running Konfyt from a console:

```
$ konfyt 
qt5ct: using qt5ct plugin
QMetaObject::connectSlotsByName: No matching signal for on_toolButton_ClearSearch_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_toolButton_RemovePatch_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_toolButton_PatchUp_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_toolButton_PatchDown_clicked()
lscp_client_create: cmd: connect: Connection refused

Konfyt ERROR, ABORTING: sfengine:processJackMidi: synthDataMap does not contain ID 64Aborted
```

qjackctl reports an XRUN and the Konfyt GUI crashes.

While attempting to determine if I could identify a faulty or problematic soundfont, I believe I've been able to determine how to reproduce this crash. Here are the steps:

1. Enable preview mode
2. Highlight a patch in the browser
3. Trigger a MIDI note on event via MIDI controller and hold the key (never generate a MIDI note off event)
4. Highlight another patch

**Comment by noedigcode** [comment]
Sorry about that! This is now fixed on the testing branch.

Thanks for reporting the bug and taking the time to narrow it down.
