### ISSUE TITLE
Feature Request: Filter Preview by MIDI channel

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#6]
Use case is as follows:

I'm playing 1 or more MIDI tracks from my DAW. Each of these tracks is triggering instruments loaded into Konfyt via their assigned MIDI channels.

Now, I'd really like to easily browse through instruments for a new part. The best way is to enable "Preview" mode. However, this has the (undesired) side-effect of routing all MIDI data to the selected instrument which is being considered. 

If the "Preview" mode could be set to function against a specific MIDI channel, all data coming in on other channels would trigger their intended instruments. This would allow the end user to preview new ideas within the context of the song.

**Comment by noedigcode** [comment]
The testing branch has been updated to add MIDI input port/channel and output bus options for preview mode. Simply use the new preview button dropdown menu.
![konfyt-preview-options](https://user-images.githubusercontent.com/11135749/71766809-c20d8380-2f0c-11ea-8cb0-f45267bec422.gif)

Note that to force your other patches to play while preview mode is enabled, you have to set the patch as always-active (from the patch menu as shown below).
![konfyt-always-active](https://user-images.githubusercontent.com/11135749/71766775-55928480-2f0c-11ea-9456-12cb5f4b95f3.gif)
