### ISSUE TITLE
Feature Request: Output audio on a per-patch basis

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#8]
The dream:

A patch contains 1 or more instruments assigned to an individual MIDI channel. That patch could then have it's output sent to 1 or more outputs (like a DAW-created audio bus).

This would mean all patches would need to be "active" which I believe is not currently the case.

This ability alone would turn Konfyt into a killer app when compared against existing soundfont players due to it's browsing, automation (app startup), instrument layering, and MIDI debugging capabilities.

**Comment by noedigcode** [comment]
I've been thinking of adding the feature to make one, more or all patches "always-active". This will require a refactor of the JACK engine code, but I already have a concept and think it would be a good feature. Hopefully I can find time soon enough, but it will take a little while.

**Comment by windowsrefund** [comment]
Glad to hear it. Thank you for the response.

**Comment by noedigcode** [comment]
I just updated the testing branch with new features:
1. Always-active mode: Each patch can be set as always-active. See the patch menu above the layer list.
2. For MIDI/SFZ/SF2 layers, the input MIDI channel can now be quickly selected from the menu, and the MIDI channel is also displayed in the button (along with the input port).

Please test, go wild, and let me know if anything breaks.

**Comment by windowsrefund** [comment]
This is great news. I'll be checking this out real soon. Thank you!

**Comment by windowsrefund** [comment]
Hello again. Sorry for the lag but I just tried to muck around and ran into an issue while trying to scan.

**Comment by noedigcode** [comment]
Scanning now fixed, sorry for that. Was due to a seemingly innocent name change.

**Comment by windowsrefund** [comment]
Thank you. Will play with this tonight.

**Comment by windowsrefund** [comment]
So this totally works now. Very, very, very nice! It's entirely possible to separate duties: Konfyt hosts soundfonts and Qtractor (or any DAW capable of managing busses) managing MIDI. This is totally awesome. I've made a video explaining it so others can see what's possible

https://exode.me/videos/watch/2001df60-9fb7-41ff-85d4-0681ba6ac349
