### ISSUE TITLE
Feature request: output to PulseOut

### ISSUE THREAD

**Issue by windowsrefund** [noedigcode/konfyt#9]
https://imgur.com/SjKuAsU.png

Possible?

**Comment by noedigcode** [comment]
Konfyt does not support PulseAudio directly.

If the PulseAudio JACK plugin is installed, PulseAudio uses JACK for playing sound anyway. In that case you should connect to system:playback_1 etc.

If you really want to output to PulseAudio, you could connect to the PulseAudio input ("PulseAudio JACK Source" in my case, I suspect it is "PulseIn" in your case), then in PulseAudio volume control, on the Input Devices tab, enable the "Set as fallback" (checkbox) button for "Jack source". This will let PulseAudio play the JACK source audio input device.
![image](https://user-images.githubusercontent.com/11135749/62847888-15223800-bcd9-11e9-9e3d-095b35f7c8d4.png)

**Comment by windowsrefund** [comment]
Thank you for the feedback. I've been pretty happy with Konfyt (and routing) for some time now and will explore this once I remember what my original situation actually was :) In the meantime, I had to take a moment to explain why I love Konfyt so much over here: https://www.twitch.tv/videos/473393221
